frontend:
  - changed-files:
      - any-glob-to-any-file: 'client/**/*'

backend:
  - changed-files:
      - any-glob-to-any-file: 'Server/**/*'

ci/cd:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'
