name: Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    name: ESLint Run (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Run ESLint
        run: |
          cd client
          npm run lint

  flake8:
    name: Flake8 Run (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: Server/requirements.txt

      - name: Install Linting Packages
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 Server --count --select=E9,F63,F7,F82 --show-source --statistics
